CREATE TABLE "TRANSACTION"
  (
    "COMPONENT_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "COMPOSITE_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
    "UPDATE_TIME"    TIMESTAMP DEFAULT SYSDATE NOT NULL ENABLE,
    CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("COMPONENT_NAME", "COMPOSITE_NAME")
  ) ;